### ISSUE TITLE
Warning: No files were found with the provided path: cv/cv.pdf. No artifacts will be uploaded.

### ISSUE THREAD

**Issue by takasurazeem** [thomas-chauvet/cv_latex#1]
Getting this error even with the fork. Am I doing anything wrong? Please help. 
```Warning: No files were found with the provided path: cv/cv.pdf. No artifacts will be uploaded.```

**Comment by thomas-chauvet** [comment]
Hello,

Thanks for the warning!

It has been fixed with last release of the github action [here](https://github.com/thomas-chauvet/latex2pdf-action/releases/tag/1.0.4).

I also fixed in this repository latex dependencies.

It works now :)
